name: golangci-lint

on: [workflow_dispatch, pull_request]

env:
  GOLANGCI_TIMEOUT: 1m0s

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Global Git config
        run: |
          git config --global url."https://${{ secrets.DV_SERVICE_ACCOUNT }}:${{ secrets.TOKEN }}@github.com".insteadOf "https://github.com"

      # Action page: https://github.com/golangci/golangci-lint-action
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout ${{ env.GOLANGCI_TIMEOUT }}
          only-new-issues: true
